### ISSUE TITLE
Oops, there has been an issue with the Google API. Check that the URL is correct, and try again.

### ISSUE THREAD

**Issue by socdevsolution** [alyssaxuu/figma-to-google-slides#4]
Which URL format does this expect ?  

**Direct Edit Mode -** 
https://docs.google.com/presentation/d/1GWIO62kuBUy9qLFq5hZE2NPhvvNrlnZocpgr
**/edit#slide=id.p** 

**URL without trailing Slash (/)**
https://docs.google.com/presentation/d/1GWIO62kuBUy9qLFq5hZE2NPhvvNrlnZocpgr

**URL with trailing Slash (/)**
https://docs.google.com/presentation/d/1GWIO62kuBUy9qLFq5hZE2NPhvvNrlnZocpgr **/**

**URL with Sharing**
https://docs.google.com/presentation/d/1FNxuU6t7-JbI18Y-CcEVt5LxW2cHySr3oJ **/edit?usp=sharing**

**Comment by alyssaxuu** [comment]
Are you using the Minified version or the Chrome Extension?

**Comment by socdevsolution** [comment]
Chrome Extension

**Comment by socdevsolution** [comment]
Using the Chrome Extension.

**Comment by socdevsolution** [comment]
Also, just curious to know, would the frame size cause any issue ?  I have 1440 x 940.
What is the limit on the number of frame that can be exported to G Slides ? I have about 150 of them.

**Comment by socdevsolution** [comment]
![image](https://user-images.githubusercontent.com/65599067/82477226-cff32800-9aec-11ea-8e03-1e99b39aa64b.png)

**Comment by alyssaxuu** [comment]
I don't think the dimensions should be an issue (I believe I made it so it stretches to fit whatever the dimensions are).

The only thing I can think of is if the presentation is under a different Google account to the one you are logged in in Chrome / logged in the first time in the extension. Otherwise it could be a rate limit issue (doubt it though), you could try exporting a couple of frames to see if it works or not.

**Comment by socdevsolution** [comment]
The account id is the same on Figma and Chrome. I tried selecting a single frame and converting to G Slide, but I get the same error :( Can you confirm what URL format is accepted ? 

![image](https://user-images.githubusercontent.com/65599067/82528519-8fc88f80-9b56-11ea-88df-16e552df68a5.png)

**Comment by alyssaxuu** [comment]
> The account id is the same on Figma and Chrome. I tried selecting a single frame and converting to G Slide, but I get the same error :( Can you confirm what URL format is accepted ?
> 
> ![image](https://user-images.githubusercontent.com/65599067/82528519-8fc88f80-9b56-11ea-88df-16e552df68a5.png)

Hmm... Do you have your frames in the first page (hierarchically) of your Figma file? Are the frames all the same dimensions? Just trying to think of ideas here. The URL seems correct to me - it automatically gets the ID from it no matter if there's /edit or any other sections afterwards.

I recommend uninstalling the extension, reinstalling, and ensuring that when you click "Sign in with Google" the account is the same one as in Google Slides (since it doesn't automatically use the same account as Chrome). Hopefully that works.

**Comment by socdevsolution** [comment]
Sure, will try that and update back here..

**Comment by socdevsolution** [comment]
I uninstalled and reinstalled, however no effect. Its the same error :( 
Below is the screenshot of how things are in the Figma file given by the designer (it this helps)

![image](https://user-images.githubusercontent.com/65599067/82530452-f5b71600-9b5a-11ea-815f-520cf4837b8d.png)

When you say frames in the first page (Hierarchically), what do you exactly mean?

**Comment by alyssaxuu** [comment]
I mean the first page in the list, but it appears to be the case.

Are the frames inside that Group by the way? I don't think the Chrome Extension is able to get those (I believe I made it so that it only takes frames which aren't nested).

I recommend trying to make a new file and a frame to see if that exports or not.

**Comment by socdevsolution** [comment]
![image](https://user-images.githubusercontent.com/65599067/82532058-28aed900-9b5e-11ea-8e38-7a4b026c3533.png)

New file, 1 Page, simple rectangle, still the same error :(

**Comment by alyssaxuu** [comment]
I meant putting the rectangle inside of a Frame ^^

**Comment by socdevsolution** [comment]
![image](https://user-images.githubusercontent.com/65599067/82532233-85aa8f00-9b5e-11ea-8878-7ec5d98a4d91.png)

This worked!

What do you reckon could be the issue with the other file ?

**Comment by alyssaxuu** [comment]
Like I mentioned, it seems that you have your frames inside a group. I would move them outside of it.

**Comment by socdevsolution** [comment]
umm okay I will ask the Designer to look into this.
Appreciate your prompt responses and support. Thank you so much. 

Stay Safe. Hope things are better there.
